package model;

public enum ActionType {
    LOGIN_BIDDER,
    LOGIN_SELLER,
    LOGIN_ADMIN,
    LOGOUT,
    REGISTER,
    BID,
    REGISTER_AUTOBID,
    UNREGISTER_AUTOBID,
    GET_BID_HISTORY,
    GET_LIST,
    GET_ITEM_DETAIL,
    NOTIFY_NEW_PRICE,
    AUCTION_END,
    AUCTION_EXTENDED,
    CREATE_ITEM,
    CHECK_DUPLICATE_NAME,
    CUSTOM_SEARCH,
    GET_SELLER_NAME,
    GOOGLE_LOGIN,

    ADMIN_GET_ALL_USERS,
    ADMIN_BAN_USER,
    ADMIN_UNBAN_USER,
    ADMIN_APPROVE_ITEM,
    ADMIN_REJECT_ITEM,
    ADMIN_GET_PENDING_ITEMS,
    ADMIN_STOP_AUCTION,
    ADMIN_DELETE_ITEM,
    ADMIN_GET_ITEM_REASON,
    ADMIN_GET_AUCTION_REASON,
    ADMIN_GET_USER_REASON,

    UPDATE_ITEM_DESCRIPTION,
    SELLER_DELETE_ITEM
}
