package model;

public enum ActionType {
    LOGIN,
    LOGOUT,
    REGISTER,
    BID,
    GET_BID_HISTORY,
    GET_LIST,
    GET_ITEM_DETAIL,
    CHECK_BALANCE,
    DEPOSIT,
    NOTIFY_NEW_PRICE,
    AUCTION_END,
    CREATE_ITEM,
    CHECK_DUPLICATE_NAME,
    CUSTOM_SEARCH,
}
